[project]
name = "ms5-asset-performance"
version = "0.1.0"
description = ""
authors = [
    {name = "mavritsa",email = "amavrits@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "numpy (>=2.4.1,<3.0.0)",
    "scipy (>=1.17.0,<2.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "pandas (>=2.1.3,<3.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
#    "probabilistic-library @ file:///C:/Users/mavritsa/Stichting%20Deltares/SITO-IS%202025%20Moonshot%205%20-%20MS5.2%20Smart%20%26%20resilient%20infra/02_Asset%20performance/02%20Case%20studies%20results/_software/PTK/probabilistic_library-25.1.1-py3-none-any.whl",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "probabilistic-library (>=26.1.1,<27.0.0)",
    "d-geolib (>=2.8.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
